
import java.io.File;
import javax.swing.JOptionPane;


/**
 *
 * @author MD.Feeham
 */
public class Createc extends javax.swing.JFrame {
int xm,ym,xx,yy;
      /**
       * Creates new form Createc
       */
      public Createc() {
            initComponents();
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jButton1 = new javax.swing.JButton();
            jLabel3 = new javax.swing.JLabel();
            name = new javax.swing.JTextField();
            jLabel2 = new javax.swing.JLabel();
            jLabel1 = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setUndecorated(true);
            getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jButton1.setBackground(new java.awt.Color(0, 0, 0));
            jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
            jButton1.setForeground(new java.awt.Color(255, 255, 255));
            jButton1.setText("SAVE");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton1ActionPerformed(evt);
                  }
            });
            getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 100, 30));

            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Internal Files/close1.jpg"))); // NOI18N
            jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel3MouseClicked(evt);
                  }
            });
            getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 50, 40));

            name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            name.setForeground(new java.awt.Color(153, 0, 0));
            name.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), java.awt.Color.gray));
            getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 530, 70));

            jLabel2.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(51, 51, 51));
            jLabel2.setText("Enter the name of special note");
            getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 440, 60));

            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Internal Files/addcbg.jpg"))); // NOI18N
            jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                  public void mouseDragged(java.awt.event.MouseEvent evt) {
                        jLabel1MouseDragged(evt);
                  }
            });
            jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mousePressed(java.awt.event.MouseEvent evt) {
                        jLabel1MousePressed(evt);
                  }
            });
            getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));

            pack();
            setLocationRelativeTo(null);
      }// </editor-fold>//GEN-END:initComponents

      private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
            setVisible(false);
            Note obj = new Note();
            obj.setVisible(true);
            obj.setmenu();
      }//GEN-LAST:event_jLabel3MouseClicked

      private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            String s=name.getText();
            String dir=Data.dir+"CFNotes\\SpecialNotes\\"+name.getText()+".txt";
            int status = Fileop.Create(dir);
            if(status==1){
                  dir=Data.dir+"CFNotes\\SpecialNotes\\List.txt";
                  String adder=" @"+s+";;";
                  Fileop.Add(dir, adder);
                  File fff = new File(Data.dir+"CFNotes\\Resources\\"+name.getText());
                  fff.mkdir();
                  Fileop.Create(Data.dir+"CFNotes\\Resources\\"+name.getText()+"\\List.txt");
                  JOptionPane.showMessageDialog(this, "New Special note was successfully created.");
                  terminate();
                  setVisible(false);
            }
            else JOptionPane.showMessageDialog(this, "Error occured! Couldn't create new note.");
      }//GEN-LAST:event_jButton1ActionPerformed

      private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
           xm=evt.getX();
            ym=evt.getY();
      }//GEN-LAST:event_jLabel1MousePressed

      private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
            xx= evt.getXOnScreen();
            yy= evt.getYOnScreen();
            
            this.setLocation(xx-xm, yy-ym);
      }//GEN-LAST:event_jLabel1MouseDragged
static void terminate(){
            Note obj = new Note();
            obj.setVisible(true);
            obj.setmenu();
}
      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(Createc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(Createc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(Createc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(Createc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new Createc().setVisible(true);
                  }
            });
      }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton jButton1;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JTextField name;
      // End of variables declaration//GEN-END:variables
}
