
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author MD.Feeham
 */
public class Editor extends javax.swing.JFrame {
      int xm,ym,xx,yy;
static int snstatus=0;
String snname;
String fp=null, rn = null;
      /**
       * Creates new form Editor
       */
      String og;
      public Editor() {
            snstatus=0;
            initComponents();
            prob.setText(Data.csprob);
            String text=Fileop.Read(Data.dir+"CFNotes\\"+Data.cscon+"\\"+Data.csprob+"\\"+Data.csprob+".txt");
            note.setText(text);    
            og=note.getText();
      }
      
      public Editor(String sn) {
            initComponents();
            snname=sn;
            snstatus++;
            prob.setText(sn);
            prob.setText(sn);
            String text=Fileop.Read(Data.dir+"CFNotes\\SpecialNotes\\"+sn+".txt");
            note.setText(text);    
            og=note.getText();
      }
      

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jLabel12 = new javax.swing.JLabel();
            jLabel11 = new javax.swing.JLabel();
            jLabel7 = new javax.swing.JLabel();
            jLabel13 = new javax.swing.JLabel();
            jLabel10 = new javax.swing.JLabel();
            jLabel9 = new javax.swing.JLabel();
            jLabel8 = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jTextField3 = new javax.swing.JTextField();
            fname = new javax.swing.JTextField();
            cf = new javax.swing.JTextField();
            save = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            jScrollPane1 = new javax.swing.JScrollPane();
            note = new javax.swing.JTextArea();
            prob = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel1 = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setUndecorated(true);
            setPreferredSize(new java.awt.Dimension(1204, 724));
            getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel12.setText("NOTE: When you write a code, inside <code> statement you dont have to use <br/> for new line. Just press enter in treditional way!");
            getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 690, -1, 20));

            jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Internal Files/redo.jpg"))); // NOI18N
            jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel11MouseClicked(evt);
                  }
            });
            getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 380, 60, 60));

            jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Internal Files/redo.jpg"))); // NOI18N
            jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel7MouseClicked(evt);
                  }
            });
            getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 60, 60));

            jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Internal Files/undo.jpg"))); // NOI18N
            jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel13MouseClicked(evt);
                  }
            });
            getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 260, 60, 60));

            jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Internal Files/undo.jpg"))); // NOI18N
            jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel10MouseClicked(evt);
                  }
            });
            getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 60, 60));

            jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Internal Files/bold.jpg"))); // NOI18N
            jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel9MouseClicked(evt);
                  }
            });
            getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, 60));

            jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Internal Files/code.jpg"))); // NOI18N
            jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel8MouseClicked(evt);
                  }
            });
            getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 60, 60));

            jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Internal Files/italic.jpg"))); // NOI18N
            jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel6MouseClicked(evt);
                  }
            });
            getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 60, 60));

            jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Internal Files/format.jpg"))); // NOI18N
            jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel4MouseClicked(evt);
                  }
            });
            getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 320, 60, 60));

            jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Internal Files/back.jpg"))); // NOI18N
            jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel3MouseClicked(evt);
                  }
            });
            getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 60, 70));

            jTextField3.setEditable(false);
            jTextField3.setBackground(new java.awt.Color(204, 255, 255));
            jTextField3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            jTextField3.setText("Add");
            jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jTextField3MouseClicked(evt);
                  }
            });
            jTextField3.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jTextField3ActionPerformed(evt);
                  }
            });
            getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 80, -1));

            fname.setEditable(false);
            fname.setBackground(new java.awt.Color(204, 255, 255));
            fname.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            fname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            fname.setText("Rename");
            fname.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        fnameMouseClicked(evt);
                  }
            });
            getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 90, -1));

            cf.setEditable(false);
            cf.setBackground(new java.awt.Color(204, 255, 255));
            cf.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
            cf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            cf.setText("Attach photo");
            cf.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        cfMouseClicked(evt);
                  }
            });
            getContentPane().add(cf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 180, 30));

            save.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
            save.setForeground(new java.awt.Color(0, 153, 51));
            save.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Internal Files/save1.jpg"))); // NOI18N
            save.setText("  SAVE");
            save.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
            save.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        saveMouseClicked(evt);
                  }
                  public void mouseEntered(java.awt.event.MouseEvent evt) {
                        saveMouseEntered(evt);
                  }
                  public void mouseExited(java.awt.event.MouseEvent evt) {
                        saveMouseExited(evt);
                  }
            });
            getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 180, 60));

            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Internal Files/close1.jpg"))); // NOI18N
            jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel5MouseClicked(evt);
                  }
            });
            getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, -1, 40));

            note.setColumns(20);
            note.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
            note.setRows(5);
            note.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
            note.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
            note.addCaretListener(new javax.swing.event.CaretListener() {
                  public void caretUpdate(javax.swing.event.CaretEvent evt) {
                        noteCaretUpdate(evt);
                  }
            });
            note.addFocusListener(new java.awt.event.FocusAdapter() {
                  public void focusGained(java.awt.event.FocusEvent evt) {
                        noteFocusGained(evt);
                  }
            });
            note.addInputMethodListener(new java.awt.event.InputMethodListener() {
                  public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                        noteCaretPositionChanged(evt);
                  }
                  public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                        noteInputMethodTextChanged(evt);
                  }
            });
            note.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
                  public void propertyChange(java.beans.PropertyChangeEvent evt) {
                        notePropertyChange(evt);
                  }
            });
            note.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
                  public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                        noteVetoableChange(evt);
                  }
            });
            jScrollPane1.setViewportView(note);

            getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 790, 550));

            prob.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
            prob.setForeground(new java.awt.Color(51, 51, 51));
            prob.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            prob.setText("Feeham and the Rabit.");
            prob.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
            getContentPane().add(prob, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 480, 70));

            jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
            getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 790, 550));

            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Internal Files/evgb.jpg"))); // NOI18N
            jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
            jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                  public void mouseDragged(java.awt.event.MouseEvent evt) {
                        jLabel1MouseDragged(evt);
                  }
            });
            jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mousePressed(java.awt.event.MouseEvent evt) {
                        jLabel1MousePressed(evt);
                  }
            });
            getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 720));

            pack();
            setLocationRelativeTo(null);
      }// </editor-fold>//GEN-END:initComponents

      private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
            if(og.equals(note.getText().toString())){
            setVisible(false);
            if(snstatus==0)
                  new View().setVisible(true);
            else
                  new View(snname).setVisible(true);
            setVisible(false);
            }
            else{
                  int d = JOptionPane.showConfirmDialog(this, "Changes have made. Do you want to save changes?");
                  if(d==0){
                        int s;
                        if(snstatus==0)
                              s = Fileop.Write(Data.dir+"CFNotes\\"+Data.cscon+"\\"+Data.csprob+"\\"+Data.csprob+".txt", note.getText());
                        else 
                              s= Fileop.Write(Data.dir+"CFNotes\\SpecialNotes\\"+snname+".txt", note.getText());
                        
                        setVisible(false);
                  }
                  else
                        setVisible(false);
            }
            
      }//GEN-LAST:event_jLabel5MouseClicked

      private void saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseEntered
            save.setForeground(Color.blue);
      }//GEN-LAST:event_saveMouseEntered

      private void saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseExited
            save.setForeground(Color.decode("#009933"));
      }//GEN-LAST:event_saveMouseExited

      private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
            ins("br");
      }//GEN-LAST:event_jLabel3MouseClicked

      private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
            save.setForeground(Color.decode("#009933"));
            int s=88;
            if(snstatus==0)
                  s = Fileop.Write(Data.dir+"CFNotes\\"+Data.cscon+"\\"+Data.csprob+"\\"+Data.csprob+".txt", note.getText());
            else 
                  s= Fileop.Write(Data.dir+"CFNotes\\SpecialNotes\\"+snname+".txt", note.getText());
            
            if(s==1){
                  JOptionPane.showMessageDialog(this, "Successfully saved.");
                  og=note.getText();}
            else 
                  JOptionPane.showMessageDialog(this, "Error occured! Could not save the changes.");
            if(snstatus==0)
            new View().setVisible(true);
            else new View(snname).setVisible(true);
            setVisible(false);
      }//GEN-LAST:event_saveMouseClicked

      private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
            ins("font");
      }//GEN-LAST:event_jLabel4MouseClicked

      private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
            ins("italic");
      }//GEN-LAST:event_jLabel6MouseClicked

      private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
            ins("bold");
      }//GEN-LAST:event_jLabel9MouseClicked

      private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
            ins("code");
      }//GEN-LAST:event_jLabel8MouseClicked

      private void notePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_notePropertyChange
            String x=note.getText();
            System.out.println(x);
            Data.urptr++;
            Data.ur[Data.urptr]=note.getText();
      }//GEN-LAST:event_notePropertyChange

      private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
            ins("undo");
      }//GEN-LAST:event_jLabel10MouseClicked

      private void noteCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_noteCaretPositionChanged
           
      }//GEN-LAST:event_noteCaretPositionChanged

      private void noteInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_noteInputMethodTextChanged
           
      }//GEN-LAST:event_noteInputMethodTextChanged

      private void noteCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_noteCaretUpdate
            Data.urptr++;
            Data.ur[Data.urptr]=note.getText();
      }//GEN-LAST:event_noteCaretUpdate

      private void noteVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_noteVetoableChange
            
      }//GEN-LAST:event_noteVetoableChange

      private void noteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_noteFocusGained
            
      }//GEN-LAST:event_noteFocusGained

      private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
            ins("undo");
      }//GEN-LAST:event_jLabel13MouseClicked

      private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
            ins("redo");
      }//GEN-LAST:event_jLabel7MouseClicked

      private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
            ins("redo");
      }//GEN-LAST:event_jLabel11MouseClicked

      private void cfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cfMouseClicked
            fname.setVisible(true);
            JFileChooser fc = new JFileChooser();
            int status=fc.showOpenDialog(fc);
            if(status == JFileChooser.APPROVE_OPTION){
                  fp = fc.getSelectedFile().getAbsolutePath();
            }
            else
                  JOptionPane.showMessageDialog(this, "Error occured choosing file!");
            cf.setText(fp);
      }//GEN-LAST:event_cfMouseClicked

      private void fnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fnameMouseClicked
            if(fp==null)
                  JOptionPane.showMessageDialog(this, "Please select a file first!");
            else{
                  rn=JOptionPane.showInputDialog("Enter the new name for file","name.jpg");
                  cf.setText(rn);
                  fname.setVisible(false);
            }
            
      }//GEN-LAST:event_fnameMouseClicked

      private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
            if(cf.getText().equals("Attach photo")&&fname.getText().equals("Rename"))
                  JOptionPane.showMessageDialog(this, "You must rename the file with a meaningfull name first!");
            else{
                  File og = new File(fp);
                  File fn = new File(Data.dir+"CFNotes\\Resources\\"+prob.getText()+"\\"+cf.getText());
                  boolean result;
                  try {
                        Files.copy(og.toPath(), fn.toPath());
                  } catch (IOException ex) {
                        Logger.getLogger(Editor.class.getName()).log(Level.SEVERE, null, ex);
                  }
                  String tn="@"+cf.getText()+";;      ";
                  Fileop.Add(Data.dir+"CFNotes\\Resources\\"+prob.getText()+"\\List.txt", tn);
                  JOptionPane.showMessageDialog(this, "File was added successfully!");
                  rn = null;
            }
      }//GEN-LAST:event_jTextField3MouseClicked

      private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_jTextField3ActionPerformed

      private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
           xm=evt.getX();
            ym=evt.getY();
      }//GEN-LAST:event_jLabel1MousePressed

      private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
            xx= evt.getXOnScreen();
            yy= evt.getYOnScreen();
            
            this.setLocation(xx-xm, yy-ym);
      }//GEN-LAST:event_jLabel1MouseDragged

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new Editor("D:\\CFNotes\\editortest.txt").setVisible(true);
                  }
            });
      }
      
      
      
      void ins(String task){
            
            if (task.equals("bold")){
                  if(note.getSelectedText()!=null)
                        note.replaceSelection("<b>"+note.getSelectedText()+"</b>\n");
                  else
                  note.replaceSelection("<b>\n\n</b>");   }
            
            else if (task.equals("italic")){
                  if(note.getSelectedText()!=null)
                        note.replaceSelection("<i>"+note.getSelectedText()+"</i>\n");
                  else
                  note.replaceSelection("<i>\n\n</i>");   }
            
            else if (task.equals("font")){
                  if(note.getSelectedText()!=null)
                        note.replaceSelection("<font color=\"\" size=\"\">"+note.getSelectedText()+"</font>\n");
                  else
                  note.replaceSelection("<font color=\"\" size=\"\">\n\n</font>");   }
            
            else if (task.equals("br")){
                  note.replaceSelection("<br/>\n");   }
            
            else if (task.equals("head")){
                  Integer s=Integer.parseInt(JOptionPane.showInputDialog(this, "Enter the size of header."));
                  if(note.getSelectedText()!=null)
                        note.replaceSelection("<h"+s.toString()+">"+note.getSelectedText()+"</h"+s.toString()+">\n");
                  else
                  note.replaceSelection("<h"+s.toString()+">"+"\n\n</h"+s.toString()+">");   }
            
            else if (task.equals("center")){
                  if(note.getSelectedText()!=null)
                        note.replaceSelection("<center>"+note.getSelectedText()+"</center>\n");
                  else
                  note.replaceSelection("<center>\n\n</center>");  }
            
            else if (task.equals("code")){
                  if(note.getSelectedText()!=null)
                        note.replaceSelection("<code>"+note.getSelectedText()+"</code>\n");
                  else
                  note.replaceSelection("<code>\n\n</code>");   }
            
            else if(task.equals("undo")){
                  if(Data.urptr<=2){}
                  else{
                        Data.urptr2++;
                        Data.ur2[Data.urptr2]=Data.ur[Data.urptr];
                        Data.urptr-=2;
                        note.setText(Data.ur[Data.urptr]);
                        Data.urptr-=2;     }
            }
            else if(task.equals("redo")){
                  if(Data.urptr2>=0){
                        note.setText(Data.ur2[Data.urptr2]);
                        Data.urptr2--;    }        
            }
            
      }
      
      
      
      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JTextField cf;
      private javax.swing.JTextField fname;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel10;
      private javax.swing.JLabel jLabel11;
      private javax.swing.JLabel jLabel12;
      private javax.swing.JLabel jLabel13;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JLabel jLabel4;
      private javax.swing.JLabel jLabel5;
      private javax.swing.JLabel jLabel6;
      private javax.swing.JLabel jLabel7;
      private javax.swing.JLabel jLabel8;
      private javax.swing.JLabel jLabel9;
      private javax.swing.JScrollPane jScrollPane1;
      private javax.swing.JTextField jTextField3;
      private javax.swing.JTextArea note;
      private javax.swing.JLabel prob;
      private javax.swing.JLabel save;
      // End of variables declaration//GEN-END:variables
}
