
import java.awt.Color;


/**
 *
 * @author MD.Feeham
 */
public class Problems extends javax.swing.JFrame {

      /**
       * Creates new form Problems
       */
      int xm,ym,xx,yy;
      public Problems() {
            initComponents();
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            d5 = new javax.swing.JLabel();
            t5 = new javax.swing.JLabel();
            t4 = new javax.swing.JLabel();
            d4 = new javax.swing.JLabel();
            d3 = new javax.swing.JLabel();
            t3 = new javax.swing.JLabel();
            d2 = new javax.swing.JLabel();
            t2 = new javax.swing.JLabel();
            t1 = new javax.swing.JLabel();
            d1 = new javax.swing.JLabel();
            p1 = new javax.swing.JLabel();
            p3 = new javax.swing.JLabel();
            p4 = new javax.swing.JLabel();
            p5 = new javax.swing.JLabel();
            p6 = new javax.swing.JLabel();
            p7 = new javax.swing.JLabel();
            p8 = new javax.swing.JLabel();
            p9 = new javax.swing.JLabel();
            p10 = new javax.swing.JLabel();
            p2 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            con = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            d6 = new javax.swing.JLabel();
            t7 = new javax.swing.JLabel();
            t6 = new javax.swing.JLabel();
            d7 = new javax.swing.JLabel();
            t8 = new javax.swing.JLabel();
            d8 = new javax.swing.JLabel();
            t10 = new javax.swing.JLabel();
            d10 = new javax.swing.JLabel();
            t9 = new javax.swing.JLabel();
            d9 = new javax.swing.JLabel();
            jLabel1 = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setUndecorated(true);
            setResizable(false);
            getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            d5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            d5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            getContentPane().add(d5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 350, 120, 17));

            t5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            t5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 100, 17));

            t4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            t4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 120, 17));

            d4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            d4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            getContentPane().add(d4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 120, 17));

            d3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            d3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            getContentPane().add(d3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, 120, 20));

            t3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            t3.setForeground(new java.awt.Color(255, 255, 255));
            t3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 120, 20));

            d2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            d2.setForeground(new java.awt.Color(255, 255, 255));
            d2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            getContentPane().add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 260, 140, 20));

            t2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            t2.setForeground(new java.awt.Color(255, 255, 255));
            t2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 140, 20));

            t1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            t1.setForeground(new java.awt.Color(255, 255, 255));
            t1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 120, -1));

            d1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            d1.setForeground(new java.awt.Color(255, 255, 255));
            d1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            getContentPane().add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 140, -1));

            p1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            p1.setForeground(new java.awt.Color(51, 51, 51));
            p1.setText("Problem 01");
            p1.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        p1MouseClicked(evt);
                  }
                  public void mouseEntered(java.awt.event.MouseEvent evt) {
                        p1MouseEntered(evt);
                  }
                  public void mouseExited(java.awt.event.MouseEvent evt) {
                        p1MouseExited(evt);
                  }
            });
            getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 420, 20));

            p3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            p3.setForeground(new java.awt.Color(51, 51, 51));
            p3.setText("Problem 03");
            p3.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        p3MouseClicked(evt);
                  }
                  public void mouseEntered(java.awt.event.MouseEvent evt) {
                        p3MouseEntered(evt);
                  }
                  public void mouseExited(java.awt.event.MouseEvent evt) {
                        p3MouseExited(evt);
                  }
            });
            getContentPane().add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 430, 20));

            p4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            p4.setForeground(new java.awt.Color(51, 51, 51));
            p4.setText("Problem 04");
            p4.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        p4MouseClicked(evt);
                  }
                  public void mouseEntered(java.awt.event.MouseEvent evt) {
                        p4MouseEntered(evt);
                  }
                  public void mouseExited(java.awt.event.MouseEvent evt) {
                        p4MouseExited(evt);
                  }
            });
            getContentPane().add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 440, -1));

            p5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            p5.setForeground(new java.awt.Color(51, 51, 51));
            p5.setText("Problem 05");
            p5.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        p5MouseClicked(evt);
                  }
                  public void mouseEntered(java.awt.event.MouseEvent evt) {
                        p5MouseEntered(evt);
                  }
                  public void mouseExited(java.awt.event.MouseEvent evt) {
                        p5MouseExited(evt);
                  }
            });
            getContentPane().add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 440, -1));

            p6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            p6.setForeground(new java.awt.Color(51, 51, 51));
            p6.setText("Problem 06");
            p6.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        p6MouseClicked(evt);
                  }
                  public void mouseEntered(java.awt.event.MouseEvent evt) {
                        p6MouseEntered(evt);
                  }
                  public void mouseExited(java.awt.event.MouseEvent evt) {
                        p6MouseExited(evt);
                  }
            });
            getContentPane().add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 440, -1));

            p7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            p7.setForeground(new java.awt.Color(51, 51, 51));
            p7.setText("Problem 07");
            p7.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        p7MouseClicked(evt);
                  }
                  public void mouseEntered(java.awt.event.MouseEvent evt) {
                        p7MouseEntered(evt);
                  }
                  public void mouseExited(java.awt.event.MouseEvent evt) {
                        p7MouseExited(evt);
                  }
            });
            getContentPane().add(p7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 450, -1));

            p8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            p8.setForeground(new java.awt.Color(51, 51, 51));
            p8.setText("Problem 08");
            p8.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        p8MouseClicked(evt);
                  }
                  public void mouseEntered(java.awt.event.MouseEvent evt) {
                        p8MouseEntered(evt);
                  }
                  public void mouseExited(java.awt.event.MouseEvent evt) {
                        p8MouseExited(evt);
                  }
            });
            getContentPane().add(p8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 436, 430, 20));

            p9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            p9.setForeground(new java.awt.Color(51, 51, 51));
            p9.setText("Problem 09");
            p9.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        p9MouseClicked(evt);
                  }
                  public void mouseEntered(java.awt.event.MouseEvent evt) {
                        p9MouseEntered(evt);
                  }
                  public void mouseExited(java.awt.event.MouseEvent evt) {
                        p9MouseExited(evt);
                  }
            });
            getContentPane().add(p9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 430, 20));

            p10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            p10.setForeground(new java.awt.Color(51, 51, 51));
            p10.setText("Problem 10");
            p10.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        p10MouseClicked(evt);
                  }
                  public void mouseEntered(java.awt.event.MouseEvent evt) {
                        p10MouseEntered(evt);
                  }
                  public void mouseExited(java.awt.event.MouseEvent evt) {
                        p10MouseExited(evt);
                  }
            });
            getContentPane().add(p10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 430, 20));

            p2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            p2.setForeground(new java.awt.Color(51, 51, 51));
            p2.setText("Problem 02");
            p2.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        p2MouseClicked(evt);
                  }
                  public void mouseEntered(java.awt.event.MouseEvent evt) {
                        p2MouseEntered(evt);
                  }
                  public void mouseExited(java.awt.event.MouseEvent evt) {
                        p2MouseExited(evt);
                  }
            });
            getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 410, 20));

            jLabel4.setBackground(new java.awt.Color(56, 142, 240));
            jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
            jLabel4.setForeground(new java.awt.Color(255, 255, 255));
            jLabel4.setText("Type");
            getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 90, 40));

            jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
            jLabel5.setForeground(new java.awt.Color(255, 255, 255));
            jLabel5.setText("Difficulty");
            getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 180, 120, 20));

            jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
            jLabel3.setText("Problems in Contest");
            getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 470, 40));

            con.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
            con.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            con.setText("EDUCATIONAL ROUND 444(DIV 3)");
            getContentPane().add(con, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 490, 70));

            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Internal Files/close1.jpg"))); // NOI18N
            jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel2MouseClicked(evt);
                  }
            });
            getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1018, 20, 50, 30));

            d6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            d6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            getContentPane().add(d6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, 120, 17));

            t7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            t7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            getContentPane().add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, 100, 17));

            t6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            t6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            getContentPane().add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, 100, 17));

            d7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            d7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            getContentPane().add(d7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 410, 120, 17));

            t8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            t8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            getContentPane().add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 436, 100, 20));

            d8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            d8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            getContentPane().add(d8, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, 120, 30));

            t10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            t10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            getContentPane().add(t10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, 120, 16));

            d10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            d10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            getContentPane().add(d10, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, 120, 20));

            t9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            t9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            getContentPane().add(t9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, 100, 17));

            d9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            d9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            getContentPane().add(d9, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 460, 120, 20));

            jLabel1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Internal Files/problemsbg.jpg"))); // NOI18N
            jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
            jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                  public void mouseDragged(java.awt.event.MouseEvent evt) {
                        jLabel1MouseDragged(evt);
                  }
            });
            jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mousePressed(java.awt.event.MouseEvent evt) {
                        jLabel1MousePressed(evt);
                  }
            });
            getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

            pack();
            setLocationRelativeTo(null);
      }// </editor-fold>//GEN-END:initComponents

      private void p1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MouseClicked
            Data.csprob=p1.getText();
            Data.cstype=t1.getText();
            Data.csdiff=d1.getText();
            new View().setVisible(true);
      }//GEN-LAST:event_p1MouseClicked

      private void p1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MouseEntered
            if(p1.getText().equals("Problem 01")){}
            else
            p1.setForeground(Color.decode("#388EF0"));
      }//GEN-LAST:event_p1MouseEntered

      private void p2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2MouseEntered
           if(p2.getText().equals("Problem 02")){}
            else
            p2.setForeground(Color.decode("#388EF0"));
      }//GEN-LAST:event_p2MouseEntered

      private void p3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p3MouseEntered
            if(p3.getText().equals("Problem 03")){}
            else
            p3.setForeground(Color.decode("#388EF0"));
      }//GEN-LAST:event_p3MouseEntered

      private void p1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MouseExited
            p1.setForeground(Color.decode("#333333"));
      }//GEN-LAST:event_p1MouseExited

      private void p2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2MouseExited
            p2.setForeground(Color.decode("#333333"));
      }//GEN-LAST:event_p2MouseExited

      private void p3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p3MouseExited
            p3.setForeground(Color.decode("#333333"));
      }//GEN-LAST:event_p3MouseExited

      private void p2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2MouseClicked
            Data.csprob=p2.getText();
            Data.cstype=t2.getText();
            Data.csdiff=d2.getText();
            new View().setVisible(true);
      }//GEN-LAST:event_p2MouseClicked

      private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
           Note obj = new Note();
            obj.setVisible(true);
            obj.setmenu();
            setVisible(false);
      }//GEN-LAST:event_jLabel2MouseClicked

      private void p4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p4MouseEntered
            if(p4.getText().equals("Problem 04")){}
            else
            p4.setForeground(Color.decode("#388EF0"));
      }//GEN-LAST:event_p4MouseEntered

      private void p5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p5MouseEntered
            if(p5.getText().equals("Problem 05")){}
            else
            p5.setForeground(Color.decode("#388EF0"));
      }//GEN-LAST:event_p5MouseEntered

      private void p6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p6MouseEntered
            if(p6.getText().equals("Problem 06")){}
            else
            p6.setForeground(Color.decode("#388EF0"));
      }//GEN-LAST:event_p6MouseEntered

      private void p7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p7MouseEntered
            if(p7.getText().equals("Problem 07")){}
            else
            p7.setForeground(Color.decode("#388EF0"));
      }//GEN-LAST:event_p7MouseEntered

      private void p8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p8MouseEntered
            if(p8.getText().equals("Problem 08")){}
            else
            p8.setForeground(Color.decode("#388EF0"));
      }//GEN-LAST:event_p8MouseEntered

      private void p9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p9MouseEntered
            if(p9.getText().equals("Problem 09")){}
            else
            p9.setForeground(Color.decode("#388EF0"));
      }//GEN-LAST:event_p9MouseEntered

      private void p10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p10MouseEntered
            if(p10.getText().equals("Problem 10")){}
            else
            p10.setForeground(Color.decode("#388EF0"));
      }//GEN-LAST:event_p10MouseEntered

      private void p4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p4MouseExited
            p4.setForeground(Color.decode("#333333"));
      }//GEN-LAST:event_p4MouseExited

      private void p5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p5MouseExited
            p5.setForeground(Color.decode("#333333"));
      }//GEN-LAST:event_p5MouseExited

      private void p6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p6MouseExited
            p6.setForeground(Color.decode("#333333"));
      }//GEN-LAST:event_p6MouseExited

      private void p7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p7MouseExited
           p7.setForeground(Color.decode("#333333"));
      }//GEN-LAST:event_p7MouseExited

      private void p8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p8MouseExited
            p8.setForeground(Color.decode("#333333"));
      }//GEN-LAST:event_p8MouseExited

      private void p9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p9MouseExited
            p9.setForeground(Color.decode("#333333"));
      }//GEN-LAST:event_p9MouseExited

      private void p10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p10MouseExited
            p10.setForeground(Color.decode("#333333"));
      }//GEN-LAST:event_p10MouseExited

      private void p3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p3MouseClicked
            Data.csprob=p3.getText();
            Data.cstype=t3.getText();
            Data.csdiff=d3.getText();
            new View().setVisible(true);
      }//GEN-LAST:event_p3MouseClicked

      private void p4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p4MouseClicked
            Data.csprob=p4.getText();
            Data.cstype=t4.getText();
            Data.csdiff=d4.getText();
            new View().setVisible(true);
      }//GEN-LAST:event_p4MouseClicked

      private void p5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p5MouseClicked
            Data.csprob=p5.getText();
            Data.cstype=t5.getText();
            Data.csdiff=d5.getText();
            new View().setVisible(true);
      }//GEN-LAST:event_p5MouseClicked

      private void p6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p6MouseClicked
            Data.csprob=p6.getText();
            Data.cstype=t6.getText();
            Data.csdiff=d6.getText();
            new View().setVisible(true);
      }//GEN-LAST:event_p6MouseClicked

      private void p7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p7MouseClicked
            Data.csprob=p7.getText();
            Data.cstype=t7.getText();
            Data.csdiff=d7.getText();
            new View().setVisible(true);
      }//GEN-LAST:event_p7MouseClicked

      private void p8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p8MouseClicked
            Data.csprob=p8.getText();
            Data.cstype=t8.getText();
            Data.csdiff=d8.getText();
            new View().setVisible(true);
      }//GEN-LAST:event_p8MouseClicked

      private void p9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p9MouseClicked
            Data.csprob=p9.getText();
            Data.cstype=t9.getText();
            Data.csdiff=d9.getText();
            new View().setVisible(true);
      }//GEN-LAST:event_p9MouseClicked

      private void p10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p10MouseClicked
            Data.csprob=p10.getText();
            Data.cstype=t10.getText();
            Data.csdiff=d10.getText();
            new View().setVisible(true);
      }//GEN-LAST:event_p10MouseClicked

      private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
            xx= evt.getXOnScreen();
            yy= evt.getYOnScreen();
            
            this.setLocation(xx-xm, yy-ym);
      }//GEN-LAST:event_jLabel1MouseDragged

      private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
            xm=evt.getX();
            ym=evt.getY();
      }//GEN-LAST:event_jLabel1MousePressed

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(Problems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(Problems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(Problems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(Problems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new Problems().setVisible(true);
                  }
            });
      }
      
      void set(String c){
            int i,j, pptr=0;
            String n="", t="", d="";
            int loca=0, locb=0, locc=0, locd=0;
            con.setText(c.toUpperCase());
            c=Fileop.Read(Data.dir+"CFNotes\\"+c+"\\Problems.txt");
            //System.out.println(c);
            
            
            for(i=0; i<c.length(); i++){
                  if(c.charAt(i)=='@'){
                        //System.out.println(c.substring(0,i));
                        for(j=i; j<c.length(); j++)
                        {
                              if(c.charAt(j)=='@')
                                    loca=j;
                              if(c.charAt(j)=='%')
                                    locb=j;
                              if(c.charAt(j)=='#')
                                    locc=j;
                              if(c.charAt(j)==' '&&c.charAt(j+3)==' '){
                                    locd=j;
                                    i=j+3;
                                    break;      }
                        }
                        t=c.substring(loca+1, locb);
                        d=c.substring(locb+1, locc);
                        n=c.substring(locc+1, locd);
                              pptr++;
                              if(pptr==1){      p1.setText(n);    t1.setText(t);    d1.setText(d);       }  
                              else if(pptr==2){      p2.setText(n);    t2.setText(t);    d2.setText(d);       }  
                              else if(pptr==3){      p3.setText(n);    t3.setText(t);    d3.setText(d);       }  
                              else if(pptr==4){      p4.setText(n);    t4.setText(t);    d4.setText(d);       }  
                              else if(pptr==5){      p5.setText(n);    t5.setText(t);    d5.setText(d);       }  
                              else if(pptr==6){      p6.setText(n);    t6.setText(t);    d6.setText(d);       }  
                              else if(pptr==7){      p7.setText(n);    t7.setText(t);    d7.setText(d);       }  
                              else if(pptr==8){      p8.setText(n);    t8.setText(t);    d8.setText(d);       }  
                              else if(pptr==9){      p9.setText(n);    t9.setText(t);    d9.setText(d);       }  
                              else if(pptr==10){      p10.setText(n);    t10.setText(t);    d10.setText(d);       }  
                  }
            }
      }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JLabel con;
      private javax.swing.JLabel d1;
      private javax.swing.JLabel d10;
      private javax.swing.JLabel d2;
      private javax.swing.JLabel d3;
      private javax.swing.JLabel d4;
      private javax.swing.JLabel d5;
      private javax.swing.JLabel d6;
      private javax.swing.JLabel d7;
      private javax.swing.JLabel d8;
      private javax.swing.JLabel d9;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JLabel jLabel4;
      private javax.swing.JLabel jLabel5;
      private javax.swing.JLabel p1;
      private javax.swing.JLabel p10;
      private javax.swing.JLabel p2;
      private javax.swing.JLabel p3;
      private javax.swing.JLabel p4;
      private javax.swing.JLabel p5;
      private javax.swing.JLabel p6;
      private javax.swing.JLabel p7;
      private javax.swing.JLabel p8;
      private javax.swing.JLabel p9;
      private javax.swing.JLabel t1;
      private javax.swing.JLabel t10;
      private javax.swing.JLabel t2;
      private javax.swing.JLabel t3;
      private javax.swing.JLabel t4;
      private javax.swing.JLabel t5;
      private javax.swing.JLabel t6;
      private javax.swing.JLabel t7;
      private javax.swing.JLabel t8;
      private javax.swing.JLabel t9;
      // End of variables declaration//GEN-END:variables
}
