
import com.sun.prism.paint.Color;
import javax.swing.DefaultListModel;



/**
 *
 * @author MD.Feeham
 */
public class View extends javax.swing.JFrame {
static int snstatus=0;
String snname;
int xm,ym,xx,yy;
      /**
       * Creates new form View
       */
      public View() {
            initComponents();
            snstatus=0;
            prob.setText(Data.csprob);
            type.setText(Data.cstype);
            diff.setText(Data.csdiff);
            new Problems().setVisible(false);
            String text=Fileop.Read(Data.dir+"CFNotes\\"+Data.cscon+"\\"+Data.csprob+"\\"+Data.csprob+".txt");
            text=Data.coder(text);
            if(!text.startsWith("<html>"))
                  text="<html>\n"+text;
            if(!text.endsWith("</html>"))
                  text=text+"\n</html>";
            note.setText(text);
            
            
            //Setting up resources
            String res[]=new String[1000];
            int rescount=0;
            String rlist=Data.dir+"CFNotes\\Resources\\"+prob.getText()+"\\List.txt";
            rlist=Fileop.Read(rlist);
            for(int i =0; i<rlist.length(); i++){
                  if(rlist.charAt(i)=='@'){
                        for(int j=i+1; j<rlist.length(); j++){
                              if(rlist.charAt(j)==';'&&rlist.charAt(j+1)==';'){
                                    res[rescount]=rlist.substring(i+1, j);
                                    rescount++;
                                    i=j+3;
                                    break;
                              }
                        }
                  }
            }
            String res2[]=new String [1000];
            int res2count=0, j;
            for(int i=0; i<res.length; i++){
                  if(res[i]==null)
                        break;
                  for(j=0; j<res2count; j++)
                        if(res2[j].equals(res[i]))
                              break;
                  
                        if(j==res2count){
                              res2[res2count]=res[i];
                              res2count++;
                        }
            }
            int listindex=0;
            DefaultListModel listop = new DefaultListModel();
            menu.setModel(listop);
            for(int i=0; i<=res2count; i++){
                  listop.add(listindex, res2[i]);
                              listindex++;
            }
      }
      
      public View(String sn){
            initComponents();
            snname=sn;
            prob.setText(sn);
            type.setText("TYPE");
            diff.setText("Special Note");
            String text=Fileop.Read(Data.dir+"CFNotes\\SpecialNotes\\"+sn+".txt");
            text=Data.coder(text);
            if(!text.startsWith("<html>"))
                  text="<html>\n"+text;
            if(!text.endsWith("</html>"))
                  text=text+"\n</html>";
            note.setText(text);
            snstatus=1;
            
            
            
                        //Setting up resources
            String res[]=new String[1000];
            int rescount=0;
            String rlist=Data.dir+"CFNotes\\Resources\\"+prob.getText()+"\\List.txt";
            rlist=Fileop.Read(rlist);
            for(int i =0; i<rlist.length(); i++){
                  if(rlist.charAt(i)=='@'){
                        for(int j=i+1; j<rlist.length(); j++){
                              if(rlist.charAt(j)==';'&&rlist.charAt(j+1)==';'){
                                    res[rescount]=rlist.substring(i+1, j);
                                    rescount++;
                                    i=j+3;
                                    break;
                              }
                        }
                  }
            }
            String res2[]=new String [1000];
            int res2count=0, j;
            for(int i=0; i<res.length; i++){
                  if(res[i]==null)
                        break;
                  for(j=0; j<res2count; j++)
                        if(res2[j].equals(res[i]))
                              break;
                  
                        if(j==res2count){
                              res2[res2count]=res[i];
                              res2count++;
                        }
            }
            int listindex=0;
            DefaultListModel listop = new DefaultListModel();
            menu.setModel(listop);
            for(int i=0; i<=res2count; i++){
                  listop.add(listindex, res2[i]);
                              listindex++;
            }
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            edit = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jPanel1 = new javax.swing.JPanel();
            jScrollPane3 = new javax.swing.JScrollPane();
            note = new javax.swing.JLabel();
            jLabel7 = new javax.swing.JLabel();
            jScrollPane1 = new javax.swing.JScrollPane();
            menu = new javax.swing.JList();
            diff = new javax.swing.JLabel();
            type = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            prob = new javax.swing.JLabel();
            jLabel1 = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setUndecorated(true);
            getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            edit.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
            edit.setForeground(new java.awt.Color(0, 153, 51));
            edit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Internal Files/edit222.jpg"))); // NOI18N
            edit.setText("   EDIT");
            edit.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
            edit.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        editMouseClicked(evt);
                  }
                  public void mouseEntered(java.awt.event.MouseEvent evt) {
                        editMouseEntered(evt);
                  }
                  public void mouseExited(java.awt.event.MouseEvent evt) {
                        editMouseExited(evt);
                  }
            });
            getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 170, 50));

            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Internal Files/close1.jpg"))); // NOI18N
            jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel4MouseClicked(evt);
                  }
            });
            getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, -1, 40));

            jPanel1.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

            jScrollPane3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
            jScrollPane3.setAutoscrolls(true);

            note.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
            note.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            note.setVerticalAlignment(javax.swing.SwingConstants.TOP);
            jScrollPane3.setViewportView(note);

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
                        .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE))
            );

            getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 790, 550));

            jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
            jLabel7.setForeground(new java.awt.Color(0, 102, 0));
            jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel7.setText("Resources");
            jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
            getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 170, 30));

            menu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
            menu.setForeground(new java.awt.Color(102, 0, 204));
            menu.setModel(new javax.swing.AbstractListModel() {
                  String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
                  public int getSize() { return strings.length; }
                  public Object getElementAt(int i) { return strings[i]; }
            });
            menu.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
            menu.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        menuMouseClicked(evt);
                  }
            });
            jScrollPane1.setViewportView(menu);

            getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 170, 130));

            diff.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
            diff.setForeground(new java.awt.Color(0, 102, 0));
            diff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            diff.setText("1600-2000");
            getContentPane().add(diff, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 170, 30));

            type.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
            type.setForeground(new java.awt.Color(102, 0, 153));
            type.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            type.setText("Type X");
            getContentPane().add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 170, 20));

            jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
            getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 170, 50));

            prob.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
            prob.setForeground(new java.awt.Color(51, 51, 51));
            prob.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            prob.setText("Feeham and the Rabit.");
            prob.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
            getContentPane().add(prob, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 480, 70));

            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Internal Files/evgb.jpg"))); // NOI18N
            jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
            jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                  public void mouseDragged(java.awt.event.MouseEvent evt) {
                        jLabel1MouseDragged(evt);
                  }
            });
            jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mousePressed(java.awt.event.MouseEvent evt) {
                        jLabel1MousePressed(evt);
                  }
            });
            getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

            pack();
            setLocationRelativeTo(null);
      }// </editor-fold>//GEN-END:initComponents

      private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
            setVisible(false);
      }//GEN-LAST:event_jLabel4MouseClicked

      private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
            if(snstatus==0)
                  new Editor().setVisible(true);
            else
                  new Editor(snname).setVisible(true);
            
            setVisible(false);
      }//GEN-LAST:event_editMouseClicked

      private void editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseEntered
            edit.setForeground(java.awt.Color.BLUE);
      }//GEN-LAST:event_editMouseEntered

      private void editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseExited
            edit.setForeground(java.awt.Color.decode("#009933"));
      }//GEN-LAST:event_editMouseExited

      private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
            Data.photoname=menu.getSelectedValue().toString();
            Data.photoparent=prob.getText().toString();
            new PhotoView().setVisible(true);
      }//GEN-LAST:event_menuMouseClicked

      private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
            xm=evt.getX();
            ym=evt.getY();
      }//GEN-LAST:event_jLabel1MousePressed

      private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
            xx= evt.getXOnScreen();
            yy= evt.getYOnScreen();
            
            this.setLocation(xx-xm, yy-ym);
      }//GEN-LAST:event_jLabel1MouseDragged

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new View().setVisible(true);
                  }
            });
      }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JLabel diff;
      private javax.swing.JLabel edit;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel4;
      private javax.swing.JLabel jLabel5;
      private javax.swing.JLabel jLabel7;
      private javax.swing.JPanel jPanel1;
      private javax.swing.JScrollPane jScrollPane1;
      private javax.swing.JScrollPane jScrollPane3;
      private javax.swing.JList menu;
      private javax.swing.JLabel note;
      private javax.swing.JLabel prob;
      private javax.swing.JLabel type;
      // End of variables declaration//GEN-END:variables
}
