
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MD.Feeham
 */
public class SpeedTest extends javax.swing.JFrame {

      /**
       * Creates new form SpeedTest
       */
      public SpeedTest() {
            initComponents();
            plus1.setEnabled(false);
            plus2.setEnabled(false);
            plus3.setEnabled(false);
            plus5.setEnabled(false);
            plus8.setEnabled(false);
            plus10.setEnabled(false);
            plus100.setEnabled(false);
            plus1000.setEnabled(false);
      }
long timea;
long timeb;
      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jPanel1 = new javax.swing.JPanel();
            jPanel2 = new javax.swing.JPanel();
            count = new javax.swing.JLabel();
            plus = new javax.swing.JButton();
            plus1 = new javax.swing.JButton();
            plus2 = new javax.swing.JButton();
            plus3 = new javax.swing.JButton();
            plus8 = new javax.swing.JButton();
            plus5 = new javax.swing.JButton();
            plus10 = new javax.swing.JButton();
            plus1000 = new javax.swing.JButton();
            plus100 = new javax.swing.JButton();
            jButton2 = new javax.swing.JButton();
            title = new javax.swing.JLabel();
            target = new javax.swing.JTextField();
            start = new javax.swing.JButton();
            jButton4 = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jPanel1.setBackground(new java.awt.Color(51, 51, 51));

            jPanel2.setBackground(new java.awt.Color(51, 51, 51));
            jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

            count.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
            count.setForeground(new java.awt.Color(204, 204, 204));
            count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            count.setText("not set");
            count.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
                  public void propertyChange(java.beans.PropertyChangeEvent evt) {
                        countPropertyChange(evt);
                  }
            });
            count.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
                  public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                        countVetoableChange(evt);
                  }
            });

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                  jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(count, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                        .addContainerGap())
            );
            jPanel2Layout.setVerticalGroup(
                  jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(count, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                        .addContainerGap())
            );

            plus.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
            plus.setText("+");
            plus.setEnabled(false);
            plus.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        plusActionPerformed(evt);
                  }
            });

            plus1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
            plus1.setText("+ 1");
            plus1.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        plus1ActionPerformed(evt);
                  }
            });

            plus2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
            plus2.setText("+ 2");
            plus2.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        plus2ActionPerformed(evt);
                  }
            });

            plus3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
            plus3.setText("+ 3");
            plus3.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        plus3ActionPerformed(evt);
                  }
            });

            plus8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
            plus8.setText("+ 8");
            plus8.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        plus8ActionPerformed(evt);
                  }
            });

            plus5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
            plus5.setText("+ 5");
            plus5.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        plus5ActionPerformed(evt);
                  }
            });

            plus10.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
            plus10.setText("+10");
            plus10.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        plus10ActionPerformed(evt);
                  }
            });

            plus1000.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
            plus1000.setText("+1000");
            plus1000.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        plus1000ActionPerformed(evt);
                  }
            });

            plus100.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
            plus100.setText("+100");
            plus100.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        plus100ActionPerformed(evt);
                  }
            });

            jButton2.setBackground(new java.awt.Color(0, 0, 0));
            jButton2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
            jButton2.setForeground(new java.awt.Color(255, 255, 255));
            jButton2.setText("TASBEEH");

            title.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
            title.setForeground(new java.awt.Color(255, 255, 255));
            title.setText("  Please set the target number :");

            target.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N

            start.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
            start.setText("START");
            start.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        startActionPerformed(evt);
                  }
            });

            jButton4.setBackground(new java.awt.Color(153, 0, 0));
            jButton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
            jButton4.setForeground(new java.awt.Color(255, 255, 255));
            jButton4.setText("GO BACK");
            jButton4.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton4ActionPerformed(evt);
                  }
            });

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addComponent(target, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(67, 67, 67)
                                                .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(40, 40, 40)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                          .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(plus1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(plus2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(plus3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(plus5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addComponent(plus8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addComponent(plus100, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(54, 54, 54)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addComponent(plus1000, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addComponent(plus10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                          .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(39, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(jButton4))
                        .addGap(57, 57, 57)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addComponent(start, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                              .addComponent(plus, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                              .addComponent(target))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                          .addComponent(plus1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(plus2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                          .addComponent(plus3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(plus5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                          .addComponent(plus10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(plus8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                          .addComponent(plus100, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(plus1000, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(53, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            );

            pack();
      }// </editor-fold>//GEN-END:initComponents

      private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
            plus.setEnabled(false);
      }//GEN-LAST:event_plusActionPerformed

      private void plus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus1ActionPerformed
            mod(1);
      }//GEN-LAST:event_plus1ActionPerformed

      private void plus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus2ActionPerformed
            mod(2);
      }//GEN-LAST:event_plus2ActionPerformed

      private void plus3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus3ActionPerformed
            mod(3);
      }//GEN-LAST:event_plus3ActionPerformed

      private void plus8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus8ActionPerformed
            mod(8);
      }//GEN-LAST:event_plus8ActionPerformed

      private void plus5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus5ActionPerformed
            mod(5);
      }//GEN-LAST:event_plus5ActionPerformed

      private void plus10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus10ActionPerformed
            mod(10);
      }//GEN-LAST:event_plus10ActionPerformed

      private void plus1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus1000ActionPerformed
            mod(1000);
      }//GEN-LAST:event_plus1000ActionPerformed

      private void plus100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus100ActionPerformed
            mod(100);
      }//GEN-LAST:event_plus100ActionPerformed

      private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
            if(target.getText().toString().length()<1)
                  JOptionPane.showMessageDialog(this, "Please set the target first!");
            else{
            plus1.setEnabled(true);
            plus2.setEnabled(true);
            plus3.setEnabled(true);
            plus5.setEnabled(true);
            plus8.setEnabled(true);
            plus10.setEnabled(true);
            plus100.setEnabled(true);
            plus1000.setEnabled(true);
            count.setText("0");
            start.setText("Started!");
            title.setText("Target is: ");
            start.setEnabled(false);
            target.setEditable(false);
            target.setBackground(Color.gray);
            timea=System.currentTimeMillis();
            }
      }//GEN-LAST:event_startActionPerformed

      private void countVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_countVetoableChange
            // TODO add your handling code here:
      }//GEN-LAST:event_countVetoableChange
private void tar(){
      target.setEditable(true);
      target.setBackground(Color.white);
}
      private void countPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_countPropertyChange
            if(start.getText().toString().equals("Started!")&&count.getText().toString().length()<9){
                  if(Integer.parseInt(count.getText().toString())>=Integer.parseInt(target.getText().toString())){
                        timeb=System.currentTimeMillis();
                        JOptionPane.showMessageDialog(this, "Done");  
                        long time=timeb-timea;
                        long sec=time/1000;
                        long min=sec/60;
                        sec = sec-min*60;
                        String s=Long.toString(min)+" : "+Long.toString(sec)+" min!";
                        count.setText(s);
                        title.setText("Please set the target number :");
                        target.setText("");
                        start.setText("Start");
                        start.setEnabled(true);
                        
            plus1.setEnabled(false);
            plus2.setEnabled(false);
            plus3.setEnabled(false);
            plus5.setEnabled(false);
            plus8.setEnabled(false);
            plus10.setEnabled(false);
            plus100.setEnabled(false);
            plus1000.setEnabled(false);
            
            tar();
                  }
            }
      }//GEN-LAST:event_countPropertyChange

      private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            new NewJFrame().setVisible(true);
            setVisible(false);
      }//GEN-LAST:event_jButton4ActionPerformed

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(SpeedTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(SpeedTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(SpeedTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(SpeedTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new SpeedTest().setVisible(true);
                  }
            });
      }
void mod(int x){
      Integer c=Integer.parseInt(count.getText().toString());
      c+=x;
      count.setText(c.toString());
      
}
      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JLabel count;
      private javax.swing.JButton jButton2;
      private javax.swing.JButton jButton4;
      private javax.swing.JPanel jPanel1;
      private javax.swing.JPanel jPanel2;
      private javax.swing.JButton plus;
      private javax.swing.JButton plus1;
      private javax.swing.JButton plus10;
      private javax.swing.JButton plus100;
      private javax.swing.JButton plus1000;
      private javax.swing.JButton plus2;
      private javax.swing.JButton plus3;
      private javax.swing.JButton plus5;
      private javax.swing.JButton plus8;
      private javax.swing.JButton start;
      private javax.swing.JTextField target;
      private javax.swing.JLabel title;
      // End of variables declaration//GEN-END:variables
}
