
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
 * @author MD.Feeham
 */
public class Createb extends javax.swing.JFrame {

      /**
       * Creates new form Createb
       */
      int xm,ym,xx,yy;
      public Createb() {
            initComponents();
      }
      public Createb(String xy) {
            initComponents();
            
            name.setText(Data.cbname);
            con.setText(Data.cbcon);
            type.setSelectedItem(Data.cbtype);
            diff.setSelectedItem(Data.cbdiff);
            setconlist();
            tag.setText(Data.selectedtag);
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            tag = new javax.swing.JTextField();
            jLabel7 = new javax.swing.JLabel();
            diff = new javax.swing.JComboBox();
            type = new javax.swing.JComboBox();
            jSeparator2 = new javax.swing.JSeparator();
            jLabel6 = new javax.swing.JLabel();
            save = new javax.swing.JButton();
            name = new javax.swing.JTextField();
            jSeparator1 = new javax.swing.JSeparator();
            jLabel5 = new javax.swing.JLabel();
            con = new javax.swing.JTextField();
            jLabel4 = new javax.swing.JLabel();
            jScrollPane1 = new javax.swing.JScrollPane();
            conlist = new javax.swing.JList();
            jLabel3 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel1 = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setUndecorated(true);
            getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            tag.setEditable(false);
            tag.setBackground(new java.awt.Color(238, 238, 238));
            tag.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
            tag.setText("Select Tags");
            tag.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        tagMouseClicked(evt);
                  }
                  public void mouseEntered(java.awt.event.MouseEvent evt) {
                        tagMouseEntered(evt);
                  }
            });
            getContentPane().add(tag, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 230, -1));

            jLabel7.setText("Must follow this style: C. Theatre square");
            getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 250, -1));

            diff.setBackground(new java.awt.Color(238, 238, 238));
            diff.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
            diff.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Difficulty", "500-800", "900-1100", "1200-1500", "1600-2000", "2100-3000", "3000++" }));
            getContentPane().add(diff, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 230, 20));

            type.setBackground(new java.awt.Color(238, 238, 238));
            type.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
            type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Type", "Type A", "Type B", "Type C", "Type D", "Type E", "Type F", "Type G", "Type H", "Type I", "Type J" }));
            getContentPane().add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 230, 20));

            jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
            getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 10, 120));

            jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jLabel6.setText("Select Problem properties: ");
            getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

            save.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
            save.setText("SAVE");
            save.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        saveActionPerformed(evt);
                  }
            });
            getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 100, -1));

            name.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
            name.setForeground(new java.awt.Color(204, 0, 0));
            name.setBorder(javax.swing.BorderFactory.createEtchedBorder());
            getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 250, 40));
            getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 580, 10));

            jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jLabel5.setText("Enter the name of problem: ");
            getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

            con.setEditable(false);
            con.setBackground(new java.awt.Color(51, 51, 51));
            con.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            con.setForeground(new java.awt.Color(255, 255, 255));
            con.setText("Select a contest from above.");
            getContentPane().add(con, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 350, 30));

            jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            jLabel4.setText("Selected contest: ");
            getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

            conlist.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        conlistMouseClicked(evt);
                  }
            });
            jScrollPane1.setViewportView(conlist);

            getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 450, 60));

            jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
            jLabel3.setText("Please select the contest under which you want to add problem: ");
            getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Internal Files/close1.jpg"))); // NOI18N
            jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel2MouseClicked(evt);
                  }
            });
            getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 50, 30));

            jLabel1.setForeground(new java.awt.Color(102, 102, 102));
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Internal Files/addcbg.jpg"))); // NOI18N
            jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
            jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                  public void mouseDragged(java.awt.event.MouseEvent evt) {
                        jLabel1MouseDragged(evt);
                  }
            });
            jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mousePressed(java.awt.event.MouseEvent evt) {
                        jLabel1MousePressed(evt);
                  }
            });
            getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

            pack();
            setLocationRelativeTo(null);
      }// </editor-fold>//GEN-END:initComponents

      private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
            setVisible(false);
            Note obj = new Note();
            obj.setVisible(true);
            obj.setmenu();
      }//GEN-LAST:event_jLabel2MouseClicked

      private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
            
            if(con.getText().equals("Select a contest from above."))
                  JOptionPane.showMessageDialog(this, "Select a Contest first!");
            else if (type.getSelectedItem().toString().length()>7)
                  JOptionPane.showMessageDialog(this, "Select a problem type!");
            else if (diff.getSelectedItem().toString().length()>10)
                  JOptionPane.showMessageDialog(this, "Select problem difficulty range!");
            else if (tag.getText().toString().equals("Select Tags"))
                  JOptionPane.showMessageDialog(this, "Select one or multiple tags!");
            else if (name.getText().toString().length()<4)
                  JOptionPane.showMessageDialog(this, "Type a valid name of problem!");
            else{
                  File file = new File(Data.dir+"CFNotes\\"+con.getText()+"\\"+name.getText());
                  boolean fs=file.mkdir();
                  Fileop.Create(Data.dir+"CFNotes\\"+con.getText()+"\\"+name.getText()+"\\"+name.getText()+".txt");
                  
                  if(fs){
                        Fileop.Add(Data.dir+"CFNotes\\"+"Type.txt", "@"+type.getSelectedItem().toString()+"#"+name.getText());
                        Fileop.Add(Data.dir+"CFNotes\\"+"Diff.txt", "@"+diff.getSelectedItem().toString()+"#"+name.getText());
                        Fileop.Add(Data.dir+"CFNotes\\"+"Tag.txt", "@"+tag.getText()+"#"+name.getText());
                        Fileop.Add(Data.dir+"CFNotes\\"+con.getText()+"\\"+"Problems.txt", "@"+type.getSelectedItem().toString()+"%"+diff.getSelectedItem().toString()+"#"+name.getText()+"           ");
                        File fff = new File(Data.dir+"CFNotes\\Resources\\"+name.getText());
                        fff.mkdir();
                        Fileop.Create(Data.dir+"CFNotes\\Resources\\"+name.getText()+"\\List.txt");
                        JOptionPane.showMessageDialog(this, "New problem addition successfull.");
                        setVisible(false);
                        
                        Data.showcon();
                        Note obj = new Note();
                        obj.setVisible(true);
                        obj.setmenu();
                        }
                  else 
                        JOptionPane.showMessageDialog(this, "Error! Problem with same name may already exists.");
                  
            setVisible(false);
            }
      }//GEN-LAST:event_saveActionPerformed

      private void conlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conlistMouseClicked
            con.setText(conlist.getSelectedValue().toString());
      }//GEN-LAST:event_conlistMouseClicked

      private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
            xm=evt.getX();
            ym=evt.getY();
      }//GEN-LAST:event_jLabel1MousePressed

      private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
            xx= evt.getXOnScreen();
            yy= evt.getYOnScreen();
            
            this.setLocation(xx-xm, yy-ym);
      }//GEN-LAST:event_jLabel1MouseDragged

      private void tagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tagMouseClicked
            Data.cbcon=con.getText();
            Data.cbdiff=diff.getSelectedItem().toString();
            Data.cbtype=type.getSelectedItem().toString();
            Data.cbname=name.getText();
            
            System.out.println(Data.cbcon);
            System.out.println(Data.cbdiff);
            System.out.println(Data.cbtype);
            System.out.println(Data.cbname);
            
            Tags obj = new Tags();
            obj.setVisible(true);
            setVisible(false);
      }//GEN-LAST:event_tagMouseClicked

      private void tagMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tagMouseEntered
            
      }//GEN-LAST:event_tagMouseEntered

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(Createb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(Createb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(Createb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(Createb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new Createb().setVisible(true);
                  }
            });
      }
      
            void setconlist(){
            int listindex=0;
            DefaultListModel listop = new DefaultListModel();
            conlist.setModel(listop);
            for(int i=0; i<=Data.conptr; i++){
                  listop.add(listindex, Data.con[i][0]);
                              listindex++;
            }
      }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JTextField con;
      private javax.swing.JList conlist;
      private javax.swing.JComboBox diff;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JLabel jLabel4;
      private javax.swing.JLabel jLabel5;
      private javax.swing.JLabel jLabel6;
      private javax.swing.JLabel jLabel7;
      private javax.swing.JScrollPane jScrollPane1;
      private javax.swing.JSeparator jSeparator1;
      private javax.swing.JSeparator jSeparator2;
      private javax.swing.JTextField name;
      private javax.swing.JButton save;
      private javax.swing.JTextField tag;
      private javax.swing.JComboBox type;
      // End of variables declaration//GEN-END:variables
}
