
import javax.swing.JOptionPane;


/**
 *
 * @author MD.Feeham
 */
public class Tags extends javax.swing.JFrame {

      int selected=0;
      
      public Tags() {
            initComponents();
            sel1.setText("Select problem related");
            sel2.setText("tags from above.");
            sel3.setText("You can select multiple");
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jPanel1 = new javax.swing.JPanel();
            add = new javax.swing.JButton();
            jScrollPane1 = new javax.swing.JScrollPane();
            list = new javax.swing.JList();
            reset = new javax.swing.JButton();
            jPanel2 = new javax.swing.JPanel();
            sel1 = new javax.swing.JTextField();
            sel2 = new javax.swing.JTextField();
            sel3 = new javax.swing.JTextField();
            jPanel3 = new javax.swing.JPanel();
            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setUndecorated(true);

            jPanel1.setBackground(new java.awt.Color(238, 238, 238));

            add.setBackground(new java.awt.Color(0, 0, 0));
            add.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
            add.setForeground(new java.awt.Color(255, 255, 255));
            add.setText("ADD TAGS");
            add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
            add.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        addActionPerformed(evt);
                  }
            });

            list.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
            list.setModel(new javax.swing.AbstractListModel() {
                  String[] strings = { "2-sat", "binary search", "bitmasks", "brute force", "chinese reminder theorem", "combinatorics", "costructive algorithms", "data structures", "dfs and similar", "divide and conquer", "dp", "dsu", "expression parsing", "fft", "flows", "games", "geometry", "graphic matching", "graph", "greedy", "hashing", "implementation", "interactive", "math", "matrices", "meet-in-the-middle", "number theory", "probabilities", "schedule", "shortest paths", "sortings", "string suffux structures", "strings", "ternary search", "trees ", "two pointers" };
                  public int getSize() { return strings.length; }
                  public Object getElementAt(int i) { return strings[i]; }
            });
            list.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        listMouseClicked(evt);
                  }
            });
            jScrollPane1.setViewportView(list);

            reset.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
            reset.setText("Reset");
            reset.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        resetActionPerformed(evt);
                  }
            });

            jPanel2.setBackground(new java.awt.Color(204, 204, 204));
            jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
            jPanel2.setForeground(new java.awt.Color(255, 255, 255));

            sel1.setEditable(false);
            sel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            sel1.setText("jTextField1");

            sel2.setEditable(false);
            sel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            sel2.setText("jTextField2");

            sel3.setEditable(false);
            sel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            sel3.setText("jTextField3");

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                  jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(sel1)
                  .addComponent(sel2)
                  .addComponent(sel3)
            );
            jPanel2Layout.setVerticalGroup(
                  jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(sel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(sel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

            jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
            jLabel1.setText("SELECT TAGS");

            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Internal Files/close1.jpg"))); // NOI18N
            jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel2MouseClicked(evt);
                  }
            });

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                  jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jLabel2))
            );
            jPanel3Layout.setVerticalGroup(
                  jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(jScrollPane1)
                              .addComponent(add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(reset))
                              .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add)
                        .addContainerGap())
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            pack();
            setLocationRelativeTo(null);
      }// </editor-fold>//GEN-END:initComponents

      private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
            sel1.setText(" ");
            sel2.setText(" ");
            sel3.setText(" ");
            selected=0;
      }//GEN-LAST:event_resetActionPerformed

      private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
            if(selected==0){
                  sel1.setText(" ");
                  sel2.setText(" ");
                  sel3.setText(" ");
            }
            selected++;
            if(selected==1)
                  sel1.setText(list.getSelectedValue().toString());
            else if(selected==2)
                  sel1.setText(sel1.getText()+", "+list.getSelectedValue().toString());
            
            if(selected==3)
                  sel2.setText(list.getSelectedValue().toString());
            else if(selected==4)
                  sel2.setText(sel2.getText()+", "+list.getSelectedValue().toString());
            
            if(selected==5)
                  sel3.setText(list.getSelectedValue().toString());
            else if(selected==6)
                  sel3.setText(sel3.getText()+", "+list.getSelectedValue().toString());
            
            if(selected>6)
                  JOptionPane.showMessageDialog(this, "Maximum tags selection limit is 6.");
      }//GEN-LAST:event_listMouseClicked

      private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
            setVisible(false);
      }//GEN-LAST:event_jLabel2MouseClicked

      private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
            String t=null;
            if(selected==0)
                  JOptionPane.showMessageDialog(this, "You must select tags first!");
            else {
                        t=sel1.getText();
                        if(sel2.getText().toString().length()>2)
                              t=t+", "+sel2.getText();
                        if(sel3.getText().toString().length()>2)
                              t=t+", "+sel3.getText();
                        Data.selectedtag=t;
                        setVisible(false);
                        Createb obj = new Createb("tag");
                        obj.setVisible(true);
            }
      }//GEN-LAST:event_addActionPerformed

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(Tags.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(Tags.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(Tags.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(Tags.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new Tags().setVisible(true);
                  }
            });
      }
      public void setcb(){
            Createb obj = new Createb();
      }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton add;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JPanel jPanel1;
      private javax.swing.JPanel jPanel2;
      private javax.swing.JPanel jPanel3;
      private javax.swing.JScrollPane jScrollPane1;
      private javax.swing.JList list;
      private javax.swing.JButton reset;
      private javax.swing.JTextField sel1;
      private javax.swing.JTextField sel2;
      private javax.swing.JTextField sel3;
      // End of variables declaration//GEN-END:variables
}
